### ISSUE TITLE
TODO post CRAN release

### ISSUE THREAD

**Issue by fabio-t** [mpallocc/auto-go#9]
- [x] add SSGSEA wrapper back, fixing it
- [x] make a proper README and github action https://r-pkgs.org/software-development-practices.html#sec-gha
- [x] make a master branch so that a stable version can maintained, while the development version can be more dodgy
- [x] make proper Releases here in Github, from the master branch
